[tools]
uv = 'latest'

[settings]
python.uv_venv_auto = true

[tasks.setup]
run = "uv run --env-file .env -- flask --app app.web init-db"
description = "Set up database with flask"

[tasks.server]
run = "uv run --env-file .env -- inv dev"
description = "run the python server"

[tasks.worker]
run = "uv run --env-file .env -- inv devworker"
description = "run the worker"

[tasks.uploader]
run = "uv run --env-file .env -- inv uploader"
description = "run the uploader"

[tasks.redis]
run = "redis-server"
description = "run redis"
